from graphics import*


intro_text = Text(Point(250,20), 'Enter the the amount of red, green, and blue that you want. \n Click the mouse when finished.')
win = GraphWin("Color Mixer", 500, 500)
red = Text(Point(120,100), 'Red')
green = Text(Point(210,100), 'Green')
blue = Text(Point(290,100), 'Blue')
red_entry = Entry(Point(160,100), 3)
green_entry = Entry(Point(255,100), 3)
blue_entry = Entry(Point(335,100), 3)
intro_text.draw(win)
red.draw(win)
green.draw(win)
blue.draw(win)
red_entry.draw(win)
green_entry.draw(win)
blue_entry.draw(win)
win.getMouse()
red_text = int(red_entry.getText())
green_text = int(green_entry.getText())
blue_text = int(blue_entry.getText())
color_box = Rectangle(Point(100,150), Point(400,450))
color_box.setFill(color_rgb(red_text, green_text, blue_text))
color_box.draw(win)
win.getMouse()
win.close()
