from graphics import*
from time import*

def main():
    type_of_story = raw_input("Do you want a happy or sad story? (happy/sad) ")
    if type_of_story == "happy" :
        win = GraphWin( 'The Man and The House',800,500)
        t1= Text(Point(400,20), "There once was a man...")
        man_head = Circle(Point(100,300), 25)
        man_head.setFill('black')
        man_body = Line(Point(100, 325),Point(100,400))
        man_rleg = Line(Point(100,400),Point(75, 450))
        man_lleg = Line(Point(100,400),Point(125, 450))
        man_arms = Line(Point(65, 350),Point(135,350))
        man_arms.draw(win)
        man_rleg.draw(win)
        man_lleg.draw(win)
        man_body.draw(win)
        man_head.draw(win)
        t1.draw(win)
        win.setBackground("white")
        win.getMouse()
        
        t1.undraw()
        t2 = Text(Point(400,20), "...who lived in a House.")
        house_main = Rectangle(Point(490,250),Point(790,450))
        house_roof = Polygon(Point(490,250),Point(640,130),Point(790,250))
        house_door = Rectangle(Point(540,300),Point(630,450))
        house_door_knob = Circle(Point(550, 375),5)
        house_door_knob.setFill('yellow')
        house_roof.setFill('red')
        house_door.setFill('brown4')
        house_main.setFill('white')
        house_main.draw(win)
        house_roof.draw(win)
        house_door.draw(win)
        house_door_knob.draw(win)
        t2.draw(win)
        win.getMouse()
        
        t2.undraw()
        t3= Text(Point(400,20), "There was some other stuff too.")
        ground = Rectangle(Point(0,450),Point(800,500))
        cloud1 = Circle(Point(45,85), 35)
        cloud2 = Circle(Point(65,60), 35)
        cloud3 = Circle(Point(90,90), 40)
        tree_trunk = Rectangle(Point(250,300),Point(280,450))
        tree_leaves = Polygon(Point(200, 330),Point(265,200),Point(330,330))
        ground.setFill('green4')
        cloud1.setFill( 'white')
        cloud2.setFill('white')
        cloud3.setFill('white')
        tree_trunk.setFill('brown2')
        tree_leaves.setFill('green3')
        ground.draw(win)
        cloud1.draw(win)
        cloud2.draw(win)
        cloud3.draw(win)
        tree_trunk.draw(win)
        tree_leaves.draw(win)
        win.setBackground("light blue")
        t3.draw(win)
        win.getMouse()
        
        t3.undraw()
        t4 = Text(Point(400,20), "The Man loved his House, and his House loved him.")
        t5 = Text(Point(400,20), "Until one day,...")
        t4.draw(win)
        for i in range (25):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        t4.undraw()
        for i in range(25):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        t5.draw(win)
        for i in range (30):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        win.getMouse()
        
        t6 = Text(Point(400,20), "well...nothing really changed. The Man and his House lived happily ever after....\nYou know, as long as he never wondered if he was just code in some computer program.")
        t5.undraw()
        t6.draw(win)
        win.getMouse()
        t7 =Text(Point(400,20), "I myself prefer sad stories...")
        t6.undraw()
        t7.draw(win)
        
        sleep(3)
        win.close()
    elif type_of_story == "sad":
        win = GraphWin( 'The Man and The House',800,500)
        t1= Text(Point(400,20), "There once was a man...")
        man_head = Circle(Point(100,300), 25)
        man_head.setFill('black')
        man_body = Line(Point(100, 325),Point(100,400))
        man_rleg = Line(Point(100,400),Point(75, 450))
        man_lleg = Line(Point(100,400),Point(125, 450))
        man_arms = Line(Point(65, 350),Point(135,350))
        man_arms.draw(win)
        man_rleg.draw(win)
        man_lleg.draw(win)
        man_body.draw(win)
        man_head.draw(win)
        t1.draw(win)
        win.setBackground("white")
        win.getMouse()
        
        t1.undraw()
        t2 = Text(Point(400,20), "...who lived in a House.")
        house_main = Rectangle(Point(490,250),Point(790,450))
        house_roof = Polygon(Point(490,250),Point(640,130),Point(790,250))
        house_door = Rectangle(Point(540,300),Point(630,450))
        house_door_knob = Circle(Point(550, 375),5)
        house_door_knob.setFill('yellow')
        house_roof.setFill('red')
        house_door.setFill('brown4')
        house_main.setFill('white')
        house_main.draw(win)
        house_roof.draw(win)
        house_door.draw(win)
        house_door_knob.draw(win)
        t2.draw(win)
        win.getMouse()
        
        t2.undraw()
        t3= Text(Point(400,20), "There was some other stuff too.")
        ground = Rectangle(Point(0,450),Point(800,500))
        cloud1 = Circle(Point(45,85), 35)
        cloud2 = Circle(Point(65,60), 35)
        cloud3 = Circle(Point(90,90), 40)
        tree_trunk = Rectangle(Point(250,300),Point(280,450))
        tree_leaves = Polygon(Point(200, 330),Point(265,200),Point(330,330))
        ground.setFill('green4')
        cloud1.setFill( 'white')
        cloud2.setFill('white')
        cloud3.setFill('white')
        tree_trunk.setFill('brown2')
        tree_leaves.setFill('green3')
        ground.draw(win)
        cloud1.draw(win)
        cloud2.draw(win)
        cloud3.draw(win)
        tree_trunk.draw(win)
        tree_leaves.draw(win)
        win.setBackground("light blue")
        t3.draw(win)
        win.getMouse()
        
        t3.undraw()
        t4 = Text(Point(400,20), "The Man loved his House, and his House loved him.")
        t5 = Text(Point(400,20), "Until one day,...")
        t4.draw(win)
        for i in range (25):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        t4.undraw()
        for i in range(25):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        t5.draw(win)
        for i in range (30):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        win.getMouse()
        
        t5.undraw()
        t6 = Text(Point(400,20), "An out of control wrecking ball destroyed his precious House!!!" )
        chain1 =Circle(Point(300,20),25)
        chain2 =Circle(Point(300,68),25)
        chain3 =Circle(Point(300,116),25)
        chain4 =Circle(Point(300,164),25)
        chain5 =Circle(Point(300,212),25)
        wrecking_ball = Circle(Point(300,310), 75)
        wrecking_ball.setFill("black")
        chain1.draw(win)
        chain2.draw(win)
        chain3.draw(win)
        chain4.draw(win)
        chain5.draw(win)
        wrecking_ball.draw(win)
        t6.draw(win)
        for j in range(250):
            chain1.move(1,0)
            chain2.move(1,0)
            chain3.move(1,0)
            chain4.move(1,0)
            chain5.move(1,0)
            wrecking_ball.move(1,0)
            sleep(0.01)
        sleep(1)
        
        t7 = Text(Point(400,20), "The Man was devastated! His house was gone forever...")
        house_broken = Polygon(Point(490,450),Point(550,430),Point(575,450),Point(640,400),Point(700,435),Point(790,450))
        house_broken.setFill('white')
        t6.undraw()
        chain1.undraw()
        chain2.undraw()
        chain3.undraw()
        chain4.undraw()
        chain5.undraw()
        wrecking_ball.undraw()
        house_main.undraw()
        house_roof.undraw()
        house_door_knob.undraw()
        house_door.undraw()
        house_broken.draw(win)
        t7.draw(win)
        win.getMouse()
        
        t7.undraw()
        t8 = Text(Point(400,20), "Heartbroken, the Man wandered aimlessly....")
        t9 = Text(Point(400,20),"Until...")
        tree_trunk.undraw()
        tree_leaves.undraw()
        house_broken.undraw()
        t8.draw(win)
        for i in range (30):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        t8.undraw()
        t9.draw(win)
        for i in range (30):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        win.getMouse()
        t9.undraw()
        t10 = Text(Point(400,20),"A Woman found the Man! The Woman was kind to the Man, and soon they became friends.")
        woman_head = Circle(Point(750,300), 25)
        woman_head.setFill('black')
        woman_body = Line(Point(750, 325),Point(750,400))
        woman_rleg = Line(Point(750,400),Point(725, 450))
        woman_lleg = Line(Point(750,400),Point(775, 450))
        woman_arms = Line(Point(715, 350),Point(785,350))
        woman_arms.draw(win)
        woman_rleg.draw(win)
        woman_lleg.draw(win)
        woman_body.draw(win)
        woman_head.draw(win)
        t10.draw(win)
        win.getMouse()
        
        for i in range(600):
            woman_arms.move(-1,0)
            woman_rleg.move(-1,0)
            woman_lleg.move(-1,0)
            woman_body.move(-1,0)
            woman_head.move(-1,0)
            sleep(0.01)
        win.getMouse()
        
        t10.undraw()
        t11 = Text(Point(400,20), "Together, the Man and the Woman returned to the Man's old, broken house." )
        house_broken.draw(win)
        tree_trunk.draw(win)
        tree_leaves.draw(win)
        t11.draw(win)
        win.getMouse()
        t11.undraw()
        t12 = Text(Point(400,20), "They worked and worked until they had rebuilt the whole thing!")
        t12.draw(win)
        for i in range (60):
            cloud1.move(1,0)
            cloud2.move(1,0)
            cloud3.move(1,0)
            sleep(0.1)
        house_main.draw(win)
        house_roof.draw(win)
        house_door.draw(win)
        house_door_knob.draw(win)
        win.getMouse()
        
        t12.undraw()
        t13= Text(Point(400,20), "But it just wasn't the same...")
        t13.draw(win)
        win.getMouse()
        
        home_sweet_home_text =Text(Point(635,270), "Home Sweet Home.")
        home_sign = Rectangle(Point( 560, 255),Point(710,295))
        home_sign.setFill('yellow1')
        home_sign.draw(win)
        home_sweet_home_text.draw(win)
        for i in range(600):
            woman_arms.move(1,0)
            woman_rleg.move(1,0)
            woman_lleg.move(1,0)
            woman_body.move(1,0)
            woman_head.move(1,0)
            man_arms.move(1,0)
            man_rleg.move(1,0)
            man_lleg.move(1,0)
            man_body.move(1,0)
            man_head.move(1,0)
            sleep(0.01)
        
                            
        
        sleep(3)
        win.close()
        print "I guess that wasn't so sad after all!"
        print
        print
        print
        print
        sleep(2)
        print "But if it makes you feel any better, Trogdor probably burninated the both of them eventually."
    else:
        print "Please enter sad or happy."
        main()
main()
        
